### ISSUE TITLE
Broken packages on PyPI.

### ISSUE THREAD

**Issue by ns-rse** [ToruNiina/libasd#14]
Currently the v1.5.5 packages for Windows on PyPI appear to be broken, the file sizes are tiny.

#13 seeks to address this, would be great if this could be merged and hopefully it will address the issue.

**Comment by ns-rse** [comment]
Thanks for merging #13 @ToruNiina whilst the [build](https://github.com/ToruNiina/libasd/actions/runs/4293772807) workflow completed but the [release](https://github.com/ToruNiina/libasd/actions/runs/3445184448) workflow didn't triggered and failed the last time it was run (roughly 4 months ago).

As a result [PyPI still only has 1.5.5 as the latest release](https://pypi.org/project/libasd/).

Would it be possible to trigger the release action again please? I'll see if I can work out what is breaking.

Thanks @ns-rse

**Comment by ns-rse** [comment]
Hi @ToruNiina 

Is there any possibility of having a look at this please? We'd like to support `.asd` file formats in [TopoStats](https://github.com/AFM-SPM/TopoStats) but because of the need for a source based distribution for some architectures we need the v1.5.6 release to be available on PyPI.

Happy to help trouble shoot any problems in the release pipeline but the logs are no longer available to review.

**Comment by ToruNiina** [comment]
I updated many ci settings, added some workaround for upstream problems, and fixed `setup.py` according to pybind11/cmake_example. Now it seems to work and you can find 1.5.6 at PyPI.

**Comment by ns-rse** [comment]
Thank you so much @ToruNiina really appreciate your ongoing support and work on this. :+1:
